# Generated by Django 4.0 on 2022-09-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_own', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'content_form',
            },
        ),
        migrations.CreateModel(
            name='ContentFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'content_format',
            },
        ),
        migrations.CreateModel(
            name='ContentPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'content_place',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_type',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=200)),
                ('short', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(max_length=200)),
                ('utm_source', models.CharField(max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_source', models.CharField(max_length=200)),
                ('utm_medium', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(blank=True, max_length=200, null=True)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('short_content', models.CharField(blank=True, max_length=800, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('text', models.TextField(blank=True, max_length=4800, null=True)),
                ('attachments', models.CharField(blank=True, max_length=200, null=True)),
                ('content_form_fk', models.ForeignKey(db_column='content_form_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.contentform')),
                ('content_format_fk', models.ForeignKey(db_column='content_format_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.contentformat')),
                ('content_place_fk', models.ForeignKey(db_column='content_place_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.contentplace')),
                ('content_type_fk', models.ForeignKey(db_column='content_type_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='smm.contenttype')),
                ('performer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rubric',
            },
        ),
        migrations.CreateModel(
            name='SocialPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('social', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'social_place',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'target',
            },
        ),
        migrations.CreateModel(
            name='UTMSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(max_length=200)),
                ('utm_source', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('disable_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('reasons', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm.post')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm.medium')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smm.posttype'),
        ),
        migrations.AddField(
            model_name='post',
            name='rubric_fk',
            field=models.ForeignKey(db_column='rubric_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.rubric'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='smm.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='target_fk',
            field=models.ForeignKey(db_column='target_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.target'),
        ),
    ]
