# Generated by Django 4.0 on 2022-09-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authdata',
            options={'verbose_name': 'Доступы'},
        ),
        migrations.AlterModelOptions(
            name='contentform',
            options={'verbose_name': 'Формат контента'},
        ),
        migrations.AlterModelOptions(
            name='contentformat',
            options={'verbose_name': 'Вид контента'},
        ),
        migrations.AlterModelOptions(
            name='contentplace',
            options={'verbose_name': 'Способы размещения контента'},
        ),
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Вид контента'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Готовые ссылки'},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name': 'UTMMedium'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'База постов'},
        ),
        migrations.AlterModelOptions(
            name='postplan',
            options={'verbose_name': 'Контент-план'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'verbose_name': 'Тип поста'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='socialplace',
            options={'verbose_name': 'Места размещения (соцсети)'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги к постам (для внутр.использования!!)'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Цель поста'},
        ),
        migrations.AlterModelOptions(
            name='utmsource',
            options={'verbose_name': 'UTMSource'},
        ),
    ]
