# Generated by Django 4.0 on 2022-09-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smm', '0002_alter_authdata_options_alter_contentform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authdata',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступы'},
        ),
        migrations.AlterModelOptions(
            name='contentform',
            options={'verbose_name': 'Формат контента', 'verbose_name_plural': 'Форматы контента'},
        ),
        migrations.AlterModelOptions(
            name='contentformat',
            options={'verbose_name': 'Вид контента', 'verbose_name_plural': 'Виды контента'},
        ),
        migrations.AlterModelOptions(
            name='contentplace',
            options={'verbose_name': 'Способ размещения контента', 'verbose_name_plural': 'Способы размещения контента'},
        ),
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Тип контента', 'verbose_name_plural': 'Типы контента'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Готовые ссылки', 'verbose_name_plural': 'Готовые ссылки'},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name': 'UTMMedium', 'verbose_name_plural': 'Список UTMMedium'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'База постов', 'verbose_name_plural': 'База постов'},
        ),
        migrations.AlterModelOptions(
            name='postplan',
            options={'verbose_name': 'Контент-план', 'verbose_name_plural': 'Контент-план'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'verbose_name': 'Тип поста', 'verbose_name_plural': 'Типы постов'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='socialplace',
            options={'verbose_name': 'Место размещения (соцсеть)', 'verbose_name_plural': 'Места размещения (соцсети)'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги к постам (для внутр.использования!!)', 'verbose_name_plural': 'Теги к постам (для внутр.использования!!)'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Цель поста', 'verbose_name_plural': 'Цели поста'},
        ),
        migrations.AlterModelOptions(
            name='utmsource',
            options={'verbose_name': 'UTMSource', 'verbose_name_plural': 'Список UTMSource'},
        ),
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_form_fk',
            field=models.ForeignKey(db_column='content_form_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.contentform', verbose_name='Формат контента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_format_fk',
            field=models.ForeignKey(db_column='content_format_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.contentformat', verbose_name='Вид контента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_place_fk',
            field=models.ForeignKey(db_column='content_place_fk', on_delete=django.db.models.deletion.CASCADE, to='smm.contentplace', verbose_name='Где размещать'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type_fk',
            field=models.ForeignKey(db_column='content_type_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='smm.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кто редактировал пост'),
        ),
        migrations.AlterField(
            model_name='post',
            name='performer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель(-и)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smm.posttype', verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rubric_fk',
            field=models.ForeignKey(db_column='rubric_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smm.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Кратко - о чем'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='smm.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='target_fk',
            field=models.ForeignKey(db_column='target_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smm.target', verbose_name='Цель поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=4800, null=True, verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок, дедлайн'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='disable_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата отмены поста'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Пост опубликован'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на пост'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда опубликовать'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='reasons',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина отмены публикации'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm.medium', verbose_name='Метка utm_source места публикации'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Стадия поста'),
        ),
    ]
