# Generated by Django 4.0 on 2022-11-14 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smm', '0003_alter_authdata_options_alter_contentform_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рассылки')),
                ('description', models.CharField(max_length=100, verbose_name='Описание рассылки')),
                ('source_type', models.CharField(choices=[('group', 'Рассылка в группы'), ('inner_person', 'Рассылка по базе'), ('outer_person', 'Рассылка с моей личной ссылкой')], default='group', max_length=100, verbose_name='Тип рассылки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name': 'UTMMedium', 'verbose_name_plural': 'Метки UTMMedium'},
        ),
        migrations.CreateModel(
            name='SourceMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Стоимость размещения')),
                ('description', models.CharField(max_length=2000, verbose_name='Короткое описание источника')),
                ('state', models.CharField(choices=[('actual', 'актуально'), ('archive', 'в архиве')], default='actual', max_length=10)),
                ('social_place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='smm.utmsource', verbose_name='Соцсеть или месседжер')),
                ('utm_medium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='smm.medium', verbose_name='метка UTMMedium')),
            ],
            options={
                'verbose_name': 'Внешний ресурс для размещения',
                'verbose_name_plural': 'Внешние ресурсы для размещения',
            },
        ),
        migrations.CreateModel(
            name='MailingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка, если есть, без меток')),
                ('outer_text', models.TextField(verbose_name='Готовый текст, сформируется автоматичесик')),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('mdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdate', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('link_messeger', models.TextField(blank=True, null=True, verbose_name='Ссылка на месседжер')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='Клиент из базы')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона клиента')),
                ('result', models.CharField(choices=[('Ожидает отправки', 'Ожидает отправки'), ('Отправлено', 'Отправлено'), ('Доставлено', 'Доставлено'), ('Прочитано', 'Прочитано'), ('Размещено (для групп)', 'Размещено (для групп)'), ('Есть ответ', 'Есть ответ'), ('Номер тренинг-центра в ЧС', 'Номер тренинг-центра в ЧС'), ('Нет в месседжере', 'Нет в месседжере')], default='Ожидает отправки', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuser', to='auth.user')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smm.mailing')),
                ('muser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='muser', to='auth.user')),
                ('puser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='puser', to='auth.user', verbose_name='Кто выполнил')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.sourcemailing', verbose_name='Источник указываем для групп')),
            ],
        ),
    ]
