# Generated by Django 4.0 on 2022-11-14 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0004_mailing_alter_medium_options_sourcemailing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
