# Generated by Django 4.0 on 2022-11-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0006_alter_mailing_options_alter_mailingdetail_cuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Список для рассылки', 'verbose_name_plural': 'Список рассылок'},
        ),
        migrations.AlterModelOptions(
            name='mailingdetail',
            options={'verbose_name': 'Клиент в рассылке', 'verbose_name_plural': 'Клиенты в рассылках'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mailingdetail',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailingdetail',
            name='client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='mailingdetail',
            name='link_messeger',
            field=models.TextField(blank=True, null=True, verbose_name='Месседжер'),
        ),
        migrations.AlterField(
            model_name='mailingdetail',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
