# Generated by Django 4.0 on 2023-02-24 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0007_alter_mailing_options_alter_mailingdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('patr', models.CharField(blank=True, max_length=250, null=True)),
                ('birthday', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 16, 0), null=True)),
                ('in_black_list', models.BooleanField(default=False, verbose_name='В черном списке')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('group', models.CharField(default='irk', max_length=10, verbose_name='База')),
                ('working', models.CharField(blank=True, max_length=250, null=True, verbose_name='Сфера деятельности')),
                ('have_kids', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('kids', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дети, подробности')),
            ],
            options={
                'db_table': 'clients_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_state',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='mailingdetail',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='source_type',
            field=models.CharField(choices=[('group', 'Рассылка в группы'), ('inner_person', 'Рассылка по базе'), ('outer_person', 'Рассылка во вне с моей личной ссылкой')], default='group', max_length=100, verbose_name='Тип рассылки'),
        ),
        migrations.AddField(
            model_name='mailingdetail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.client', verbose_name='Клиент'),
        ),
    ]
