# Generated by Django 4.0 on 2023-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0008_client_state_remove_mailingdetail_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_group', models.BooleanField(default=False, verbose_name='Группа в viber')),
                ('tg_group', models.BooleanField(default=False, verbose_name='Группа в тг')),
                ('wa_group', models.BooleanField(default=False, verbose_name='Группа в whatsapp')),
                ('viber', models.BooleanField(default=False)),
                ('tg', models.BooleanField(default=False, verbose_name='telegram')),
                ('wa', models.BooleanField(default=False, verbose_name='whatsapp')),
                ('sms', models.BooleanField(default=False, verbose_name='смс')),
                ('call', models.BooleanField(default=False, verbose_name='Звонить')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'db_table': 'client_mailing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assisting', models.BooleanField(default=False, verbose_name='Клиент ассистировал')),
                ('future_assisting', models.BooleanField(default=False, verbose_name='Хочет на ассистирование')),
                ('is_base_course', models.BooleanField(default=False, verbose_name='Курсовой')),
                ('course_candidate', models.TextField(blank=True, null=True, verbose_name='Кандидаты на курс')),
                ('is_school_level_1', models.BooleanField(default=False, verbose_name='Выпускник ИШ1')),
                ('is_school_level_2', models.BooleanField(default=False, verbose_name='Выпускник ИШ2')),
                ('is_school_level_3', models.BooleanField(default=False, verbose_name='Выпускник ИШ3')),
                ('tg', models.BooleanField(default=False, verbose_name='Выпускник терапевтической группы')),
            ],
            options={
                'db_table': 'client_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaingUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_source', models.CharField(max_length=200)),
                ('utm_campaing', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UTMCampaing',
                'verbose_name_plural': 'Метки UTMCampaing',
                'db_table': 'smm_utm_campaign',
            },
        ),
        migrations.AlterModelOptions(
            name='socialplace',
            options={'verbose_name': 'Место размещения (соцсеть или лэндинг)', 'verbose_name_plural': 'Места размещения (соцсети и сайты)'},
        ),
    ]
