# Generated by Django 4.0 on 2023-07-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0009_clientmailing_clientproducts_campaingutm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UTMCampaing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.campaingutm', verbose_name='utm_campaing (у кого публикуем)')),
                ('UTMMedium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.medium', verbose_name='utm_medium (как публикуем)')),
                ('UTMSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.utmsource', verbose_name='utm_source (где публикуем)')),
            ],
            options={
                'verbose_name': 'Готовый набор UTM меток',
                'verbose_name_plural': 'Готовый набор UTM меток',
                'db_table': 'smm_utms',
            },
        ),
    ]
