# Generated by Django 4.0 on 2023-07-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0011_campaingutm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Готовая ссылка с utm-метками', 'verbose_name_plural': 'Готовые ссылки с utm-метками'},
        ),
        migrations.AddField(
            model_name='socialplace',
            name='UTMCampaing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.campaingutm', verbose_name='utm_campaing (в какой группе или у кого)'),
        ),
        migrations.AddField(
            model_name='socialplace',
            name='UTMSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.utmsource', verbose_name='utm_source (где публикуем)'),
        ),
        migrations.AddField(
            model_name='sourcemailing',
            name='utm_campaing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.campaingutm', verbose_name='метка UTMCampaing'),
        ),
    ]
