# Generated by Django 4.0 on 2023-07-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0012_alter_links_options_socialplace_utmcampaing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utms',
            name='UTMCampaing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.campaingutm', verbose_name='utm_campaing (Название кампании (расписание, анонс))'),
        ),
        migrations.AlterField(
            model_name='utms',
            name='UTMMedium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.medium', verbose_name='utm_medium (Тип трафика)'),
        ),
        migrations.AlterField(
            model_name='utms',
            name='UTMSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.utmsource', verbose_name='utm_source (в какой соцсети)'),
        ),
    ]
