# Generated by Django 4.0 on 2023-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0013_alter_utms_utmcampaing_alter_utms_utmmedium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContentUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('utm_type_content', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UTM Type Content (post/stories/header)',
                'verbose_name_plural': 'Метки UTM Type Content',
                'db_table': 'smm_utm_type_Content',
            },
        ),
        migrations.CreateModel(
            name='TypeSourceUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('utm_type_source', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UTM Type Source (тип ресурса, группа, канал, сообщение или что)',
                'verbose_name_plural': 'Метки UTM Type Source',
                'db_table': 'smm_utm_type_source',
            },
        ),
    ]
