# Generated by Django 4.0 on 2023-07-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0014_typecontentutm_typesourceutm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialplace',
            name='UTMCampaing',
        ),
        migrations.RemoveField(
            model_name='socialplace',
            name='UTMSource',
        ),
        migrations.RemoveField(
            model_name='sourcemailing',
            name='social_place',
        ),
        migrations.RemoveField(
            model_name='sourcemailing',
            name='utm_campaing',
        ),
        migrations.RemoveField(
            model_name='sourcemailing',
            name='utm_medium',
        ),
        migrations.AddField(
            model_name='links',
            name='utm_type_source',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialplace',
            name='utm_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.medium', verbose_name='utm_medium (Тип трафика)'),
        ),
        migrations.AddField(
            model_name='socialplace',
            name='utm_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.utmsource', verbose_name='utm_source (где публикуем)'),
        ),
        migrations.AddField(
            model_name='socialplace',
            name='utm_type_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.typesourceutm', verbose_name='utm_type_source (группа/страница/канал/чат)'),
        ),
        migrations.DeleteModel(
            name='UTMs',
        ),
    ]
