# Generated by Django 4.0 on 2023-07-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0015_remove_socialplace_utmcampaing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialplace',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='socialplace',
            name='utm_source',
        ),
        migrations.RemoveField(
            model_name='socialplace',
            name='utm_type_source',
        ),
    ]
