# Generated by Django 4.0 on 2023-07-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smm', '0017_socialplace_utm_medium_socialplace_utm_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaingutm',
            name='user',
        ),
        migrations.AddField(
            model_name='medium',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='чья метка (из команды)'),
        ),
    ]
