# Generated by Django 4.0 on 2023-07-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0018_remove_campaingutm_user_medium_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaingutm',
            options={'verbose_name': 'UTMCampaign', 'verbose_name_plural': 'Метки UTMCampaign'},
        ),
        migrations.RenameField(
            model_name='campaingutm',
            old_name='utm_campaing',
            new_name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='sourcemailing',
            name='utm_campaing',
        ),
        migrations.RemoveField(
            model_name='utms',
            name='utm_campaing',
        ),
        migrations.AddField(
            model_name='links',
            name='utm_type_content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_type_content'),
        ),
        migrations.AddField(
            model_name='sourcemailing',
            name='utm_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.campaingutm', verbose_name='utm_campaign (Название кампании))'),
        ),
        migrations.AddField(
            model_name='utms',
            name='utm_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smm.campaingutm', verbose_name='utm_campaign (Название кампании))'),
        ),
        migrations.AlterField(
            model_name='links',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_campaign'),
        ),
        migrations.AlterField(
            model_name='links',
            name='utm_content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_content'),
        ),
        migrations.AlterField(
            model_name='links',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_medium'),
        ),
        migrations.AlterField(
            model_name='links',
            name='utm_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_source'),
        ),
        migrations.AlterField(
            model_name='links',
            name='utm_term',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_term'),
        ),
        migrations.AlterField(
            model_name='links',
            name='utm_type_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_type_source'),
        ),
        migrations.AlterModelTable(
            name='campaingutm',
            table='smm_utm_campaing',
        ),
    ]
