# Generated by Django 4.0 on 2023-07-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0019_alter_campaingutm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='текст рассылки без меток'),
        ),
    ]
