# Generated by Django 4.0 on 2022-09-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Подробное описание задачи')),
                ('links', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылки')),
                ('files', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылки на файлы')),
                ('red_line', models.DateTimeField(null=True, verbose_name='Срок, к какому выполнить')),
                ('dead_line', models.DateTimeField(null=True, verbose_name='Крайний срок')),
                ('priorety', models.IntegerField(default=5, verbose_name='Важность по шкале 1-10')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to='auth.user', verbose_name='Кто поставил задачу')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_performer', to='auth.user', verbose_name='Исполнитель')),
            ],
        ),
    ]
