# Generated by Django 4.0 on 2022-09-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
