# Generated by Django 4.0 on 2022-09-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_position_profile_birthday_profile_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='position',
            name='instruction',
            field=models.CharField(blank=True, help_text='Ссылка на инструкцию к должности', max_length=500, null=True, verbose_name='Должностные обязательства'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regalia',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Регалии и звания'),
        ),
        migrations.CreateModel(
            name='ProfilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата начала работы')),
                ('end_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата окончания работы')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.position')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'db_table': 'profile_position',
            },
        ),
    ]
