# Generated by Django 4.0 on 2022-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_end_date_remove_profile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileposition',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
    ]
