# Generated by Django 4.0 on 2022-09-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие'},
        ),
        migrations.AlterModelOptions(
            name='eventplan',
            options={'verbose_name': 'План мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место'},
        ),
        migrations.AddField(
            model_name='event',
            name='prev_step',
            field=models.TextField(blank=True, null=True, verbose_name='Предыдущий шаг по продуктам'),
        ),
        migrations.AlterField(
            model_name='event',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Какие боли закрывает?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='continuance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.IntegerField(default=5, verbose_name='Сколько человек по плану'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='decsription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=200, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='next_step',
            field=models.TextField(blank=True, null=True, verbose_name='Следующий шаг по продуктам'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=200, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='is_period',
            field=models.BooleanField(default=False, verbose_name='Это периодичное мероприятие?'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Введите период'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.place', verbose_name='Где'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Кто ведёт'),
        ),
        migrations.AlterField(
            model_name='place',
            name='addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
    ]
