# Generated by Django 4.0 on 2022-09-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventstate_eventtype_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decsription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='eventstate',
            old_name='decsription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='decsription',
            new_name='description',
        ),
    ]
