# Generated by Django 4.0 on 2022-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_decsription_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplan',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала'),
        ),
    ]
