# Generated by Django 4.0 on 2023-07-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_alter_eventplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.CharField(default='2022/2023', max_length=100, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на лендинг'),
        ),
    ]
