# Generated by Django 4.0 on 2023-07-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_season_event_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='season',
        ),
        migrations.AddField(
            model_name='eventplan',
            name='season',
            field=models.CharField(default='2023/2024', max_length=100, verbose_name='Сезон'),
        ),
    ]
