# Generated by Django 4.0 on 2023-07-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_season_eventplan_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventplan',
            name='season',
        ),
    ]
