# Generated by Django 4.0 on 2023-07-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventplan_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplan',
            name='season',
            field=models.CharField(default='2023/2024', max_length=100, verbose_name='Сезон'),
        ),
    ]
