# Generated by Django 4.0 on 2023-07-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventplan_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткое описание (до 500 знаков)'),
        ),
    ]
