# Generated by Django 4.0 on 2023-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на лендинг (перекроет ссылку тренинга)'),
        ),
    ]
