# Generated by Django 4.0 on 2023-07-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventplan_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplan',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Введите период (в днях)'),
        ),
    ]
