# Generated by Django 4.0 on 2022-09-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
                ('source', models.CharField(max_length=250, verbose_name='Источник связи')),
                ('comment', models.TextField(blank=True, null=True)),
                ('note', models.TextField(verbose_name='Резюме разговора')),
                ('stage', models.CharField(max_length=250, verbose_name='Этап')),
                ('target', models.CharField(blank=True, max_length=250, null=True, verbose_name='Целевое действие')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Координатор')),
            ],
        ),
    ]
