# Generated by Django 4.0 on 2022-11-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='Клиент')),
                ('event_plan_id', models.IntegerField(verbose_name='Мероприятие')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'История посещений мероприятий',
                'verbose_name_plural': 'История посещений мероприятий',
                'db_table': 'client_event_history',
            },
        ),
        migrations.AlterModelOptions(
            name='lid',
            options={'verbose_name': 'Входящие обращения (Заявки)', 'verbose_name_plural': 'Заявка'},
        ),
        migrations.RemoveField(
            model_name='lid',
            name='note',
        ),
        migrations.RemoveField(
            model_name='lid',
            name='stage',
        ),
        migrations.AddField(
            model_name='lid',
            name='block_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код блока'),
        ),
        migrations.AddField(
            model_name='lid',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='lid',
            name='form_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма на сайте'),
        ),
        migrations.AddField(
            model_name='lid',
            name='lid_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код заявки'),
        ),
        migrations.AddField(
            model_name='lid',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lid',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='lid',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_campaign'),
        ),
        migrations.AddField(
            model_name='lid',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_medium'),
        ),
        migrations.AddField(
            model_name='lid',
            name='utm_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_source'),
        ),
        migrations.AddField(
            model_name='lid',
            name='utm_term',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_term'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='action',
            field=models.CharField(max_length=250, verbose_name='Действие: позвонил, написал, оставил заявку через сайт и тд'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Клиент (если новый, то пусто)'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания (внутренние)'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='event_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мероприятие (пусто, если клиент не знает чего хочет'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='source',
            field=models.CharField(max_length=250, verbose_name='Источник связи, ссылка'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Координатор, кто берётся работать'),
        ),
        migrations.AlterModelTable(
            name='lid',
            table='lid',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('action', models.CharField(max_length=250, verbose_name='Действие координатора')),
                ('note', models.TextField(verbose_name='Резюме общения')),
                ('stage', models.CharField(max_length=250, verbose_name='Этап')),
                ('lid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lid_actions', to='crm.lid')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Координатор, кто берётся работать')),
            ],
            options={
                'verbose_name': 'История взаимодействий с клиентами',
                'verbose_name_plural': 'История взаимодействий с клиентами',
                'db_table': 'action',
            },
        ),
    ]
