# Generated by Django 4.0 on 2022-11-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_previouslist_alter_action_lid_previouslistclient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previouslist',
            options={'verbose_name': 'Список на мероприятие', 'verbose_name_plural': 'Списки на мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='previouslistclient',
            options={'verbose_name': 'Клиент из списка', 'verbose_name_plural': 'Клиенты из списков'},
        ),
    ]
