# Generated by Django 4.0 on 2023-02-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0004_alter_previouslist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Координатор, кто берётся работать, ответственный'),
        ),
        migrations.AlterField(
            model_name='previouslist',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
