# Generated by Django 4.0 on 2023-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_action_worker_alter_previouslist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Вебхук',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
