# Generated by Django 4.0 on 2023-07-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_webhook_cdate_webhook_formid_webhook_formname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='utm_content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_content'),
        ),
        migrations.AddField(
            model_name='lid',
            name='utm_type_content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_type_content'),
        ),
        migrations.AddField(
            model_name='lid',
            name='utm_type_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utm_type_source'),
        ),
    ]
