# Generated by Django 4.0 on 2023-07-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_action_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouslist',
            name='event_id',
            field=models.ImageField(null=True, upload_to='', verbose_name='Мероприятие без даты'),
        ),
        migrations.AddField(
            model_name='previouslist',
            name='event_plan_id',
            field=models.IntegerField(null=True, verbose_name='Мероприятие с известной датой'),
        ),
    ]
