# Generated by Django 4.0 on 2023-08-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_event_eventplan_eventstate_eventtype_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouslist',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.event', verbose_name='Мероприятие без даты'),
        ),
        migrations.AlterField(
            model_name='previouslist',
            name='event_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.eventplan', verbose_name='Мероприятие с известной датой'),
        ),
    ]
