# Generated by Django 4.0 on 2023-08-02 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_previouslist_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('patr', models.CharField(blank=True, max_length=250, null=True)),
                ('birthday', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 16, 0), null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('in_black_list', models.BooleanField(default=False, verbose_name='В черном списке')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('group', models.CharField(default='irk', max_length=10, verbose_name='База')),
                ('working', models.CharField(blank=True, max_length=250, null=True, verbose_name='Сфера деятельности')),
                ('have_kids', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('kids', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дети, подробности')),
            ],
            options={
                'db_table': 'clients_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_state',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='previouslistclient',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
        ),
    ]
