# Generated by Django 4.0 on 2023-08-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_client_state_alter_previouslistclient_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previouslistclient',
            old_name='client_id',
            new_name='client',
        ),
    ]
