# Generated by Django 4.0 on 2023-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_rename_client_id_previouslistclient_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_group', models.BooleanField(default=False, verbose_name='Группа в viber')),
                ('tg_group', models.BooleanField(default=False, verbose_name='Группа в тг')),
                ('wa_group', models.BooleanField(default=False, verbose_name='Группа в whatsapp')),
                ('viber', models.BooleanField(default=False)),
                ('tg', models.BooleanField(default=False, verbose_name='telegram')),
                ('wa', models.BooleanField(default=False, verbose_name='whatsapp')),
                ('sms', models.BooleanField(default=False, verbose_name='смс')),
                ('call', models.BooleanField(default=False, verbose_name='Звонить')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'db_table': 'client_mailing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assisting', models.BooleanField(default=False, verbose_name='Клиент ассистировал')),
                ('future_assisting', models.BooleanField(default=False, verbose_name='Хочет на ассистирование')),
                ('is_base_course', models.BooleanField(default=False, verbose_name='Курсовой')),
                ('course_candidate', models.TextField(blank=True, null=True, verbose_name='Кандидаты на курс')),
                ('is_school_level_1', models.BooleanField(default=False, verbose_name='Выпускник ИШ1')),
                ('is_school_level_2', models.BooleanField(default=False, verbose_name='Выпускник ИШ2')),
                ('is_school_level_3', models.BooleanField(default=False, verbose_name='Выпускник ИШ3')),
                ('tg', models.BooleanField(default=False, verbose_name='Выпускник терапевтической группы')),
            ],
            options={
                'db_table': 'client_products',
                'managed': False,
            },
        ),
    ]
