# Generated by Django 4.0 on 2022-09-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('patr', models.CharField(blank=True, max_length=250, null=True)),
                ('birthday', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('in_black_list', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_state',
            },
        ),
        migrations.CreateModel(
            name='ClientProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assisting', models.BooleanField(default=False)),
                ('future_assisting', models.BooleanField(default=True)),
                ('is_base_course', models.BooleanField(default=False)),
                ('course_candidate', models.TextField(blank=True, null=True)),
                ('is_school_level_1', models.BooleanField(default=False)),
                ('is_school_level_2', models.BooleanField(default=False)),
                ('is_school_level_3', models.BooleanField(default=False)),
                ('tg', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'client_products',
            },
        ),
        migrations.CreateModel(
            name='ClientMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_group', models.BooleanField(default=False)),
                ('tg_group', models.BooleanField(default=False)),
                ('wa_group', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'client_mailing',
            },
        ),
        migrations.CreateModel(
            name='ClientInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=250, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'client_interest',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.state'),
        ),
    ]
