# Generated by Django 4.0 on 2022-09-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_options_alter_clientinterest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinterest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientmailing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='clientproducts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.client'),
        ),
    ]
