# Generated by Django 4.0 on 2022-09-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_options_alter_clientinterest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
