# Generated by Django 4.0 on 2022-10-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.CharField(default='irk', max_length=10),
        ),
    ]
