# Generated by Django 4.0 on 2022-10-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.state'),
        ),
    ]
