# Generated by Django 4.0 on 2022-10-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproducts',
            name='future_assisting',
            field=models.BooleanField(default=False, verbose_name='Хочет на ассистирование'),
        ),
    ]
