# Generated by Django 4.0 on 2022-11-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0011_alter_clientproducts_future_assisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-01', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='cuser',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='client_cuser', to='auth.user', verbose_name='Кто добавил в базу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='have_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='kids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='client',
            name='muser',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='client_muser', to='auth.user', verbose_name='Кто обновил информацию'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='working',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
    ]
