# Generated by Django 4.0 on 2022-11-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_cdate_client_cuser_client_have_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
