# Generated by Django 4.0 on 2022-11-24 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 16, 0), null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.CharField(default='irk', max_length=10, verbose_name='База'),
        ),
        migrations.AlterField(
            model_name='client',
            name='have_kids',
            field=models.BooleanField(default=False, verbose_name='Есть дети'),
        ),
        migrations.AlterField(
            model_name='client',
            name='in_black_list',
            field=models.BooleanField(default=False, verbose_name='В черном списке'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kids',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дети, подробности'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.state', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='working',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Сфера деятельности'),
        ),
    ]
