# Generated by Django 4.0 on 2022-11-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0014_alter_client_birthday_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cuser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_cuser', to='auth.user', verbose_name='Кто добавил в базу'),
        ),
        migrations.AlterField(
            model_name='client',
            name='muser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_muser', to='auth.user', verbose_name='Кто обновил информацию'),
        ),
    ]
